version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    executor: node/default

    steps:
      - checkout
      - node/install-packages:
        pkg-manager: npm
      - run:
        comman: npm start
        name: start server

workflows:
  build:
    jobs:
      - run
      - build:
        requires:
          - run
        filters:
          branches:
            only: main
