version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  run:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm start
          name: Run program
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - run
